# Each new term in the Fibonacci sequence is generated by adding
# the previous two terms. By starting with 1 and 2, the first 10
# terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values
# do not exceed four million, find the sum of the even-valued terms.

def find_fib_numbers count
	fib_numbers = []
	a = 0
	b = 1
	count.times do
		c = a + b
		fib_numbers.push(c)
		a, b = b, c
	end
	return fib_numbers
end

def fib_numbers_less_than number
	fib_numbers = [0]
	i = 1
	while fib_numbers[-1] < number
		fib_numbers = find_fib_numbers(i)
		i += 1
	end
	fib_numbers
end


fib_numbers = fib_numbers_less_than(4000000)

fib_numbers = fib_numbers.select{|number| number % 2 == 0}

puts fib_numbers.inject {|sum, x| sum + x}

# => 4613732